### ISSUE TITLE
FileNotFound error

### ISSUE THREAD

**Issue by SiddAjriY2Jaccount** [pgebert/autonomous_car_simulation#1]
Hello,

While executing the command `python model.py` the following error occurs:
```
FileNotFoundError: [Errno 2] File driving_log.csv does not exist: 'driving_log.csv'
```

Could you help me understand the reasoning behind this error/how to resolve it? Thanks

**Comment by pgebert** [comment]
Hey, 

before training the model you have to generate the training data (images and driving_log.csv) with the Udacity Self-Driving Car Simulator. I probably should provide a more meaningful error message - sorry for that. 

Best regards, 
Patrick
